### ISSUE TITLE
Support client code and environment templating in ARM parameter file names

### ISSUE THREAD

**Issue by gnadaban** [Food-X-Technologies/foodx_devops_tools#75]
**Is your feature request related to a problem? Please describe.**
It's tedious to have to hardcode client and environment information in the puff map file.

**Describe the solution you'd like**
Deploy manager should support templating in puff file fields, so that this:

```yaml
puff_map:
  frames:
    coredata:
      applications:
        actiongroup:
          arm_parameters_files:
            ftr:
              egms_fdx_devd:
                coredata-team-monitor-integrations: actiongroup.coredata-team-monitor-integrations.fdx.egms_fdx_devd.json
```

Could be templated like this:

```yaml
puff_map:
  frames:
    coredata:
      applications:
        actiongroup:
          arm_parameters_files:
            ftr:
              egms_fdx_devd:
                coredata-team-monitor-integrations: actiongroup.coredata-team-monitor-integrations.${CLIENT_CODE}.${SUBSCRIPTION}.json
```

This would:
1. Simplify maintenance of puff files because we would not have to hardcode the same redundant information all over that is already available within the context of the deployment
1. Allow us to have a single, default Puff Map, with the client-specific ones becoming optional in case we want to deploy only a subset of resources
1. Allow us to rely on the common shared Puff map to do feature branch deployments with pseudo-random client codes per branch
